version: '3.8'

services:
  tenant-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_MULTIPLE_DATABASES: ${TENANT_DBS:-tenant1_db,tenant2_db}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - tenant-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tenant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tenant-data:

networks:
  tenant-network:
    name: tenant-network 