version: '3.8'

services:
  config-db:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: config_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - config-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - config-network
    command: ["mongod", "--auth"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  config-data:

networks:
  config-network:
    name: config-network 