global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "campaign-processor"
    scrape_interval: 10s
    static_configs:
      - targets: ["campaign-processor:8080"]
        labels:
          service: "campaign-processor"

  - job_name: "marketing-api"
    scrape_interval: 10s
    static_configs:
      - targets: ["marketing-api:8000"]
        labels:
          service: "marketing-api"

  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
        labels:
          service: "mongodb" 